# Generated by Django 4.1.2 on 2022-10-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Income', 'Income'), ('Expenditure', 'Expenditure')], default='Income', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField(default='2000-01-01')),
                ('description', models.CharField(max_length=150)),
            ],
        ),
    ]
